name: Deploy to Local Minikube

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
  workflow_dispatch:  # Optional: allows manual trigger

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          cp $HOME/.kube/config $HOME/.kube/config  # Uses current user's kubeconfig

      - name: Set KUBECONFIG environment variable
        run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Debug runner user and kubeconfig
        run: |
          echo "Running as user: $(whoami)"
          echo "Home directory: $HOME"
          echo "Kubeconfig:"
          cat $HOME/.kube/config

      - name: Debug Kubeconfig and Cluster
        run: |
          echo "Current context:"
          kubectl config current-context
          echo "Available deployments:"
          kubectl get deployments -n my-namespace

      - name: Deploy backend to Minikube
        run: |
          kubectl rollout restart deployment backend-deployment -n my-namespace
