name: Deploy to Local Minikube

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
  workflow_dispatch: # Optional: allows manual triggers to runn
  # testing the app

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          echo "Creating ~/.kube directory and copying kubeconfig"
          mkdir -p $HOME/.kube
          cp /home/sajad-ahmed/.kube/config $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Set KUBECONFIG environment variable
        run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Debug runner user and kubeconfig
        run: |
          echo "Running as user: $(whoami)"
          echo "Home directory: $HOME"
          echo "Kubeconfig:"
          cat $HOME/.kube/config

      - name: Verify kubectl access
        run: |
          echo "kubectl version:"
          kubectl version --client
          echo "Cluster Info:"
          kubectl cluster-info

      - name: Debug Kubeconfig and Cluster
        run: |
          echo "Current context:"
          kubectl config current-context
          echo "Available deployments in 'my-namespace':"
          kubectl get deployments -n my-namespace || echo "No deployments found."

      - name: Deploy backend to Minikube
        run: |
          kubectl rollout restart deployment backend-deployment -n my-namespace
# dummy change
